version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.17

    working_directory: ~/tslint-report

    steps:
      - checkout

      - run:
          name: report tool versions
          command: |
            npm --version
            node --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Perform tslint Check
          command: npm run tslint

      - run:
          name: check if the build in dist up to date
          command: |
            npm run build
            git add . # make sure line endings are sanitized by git
            git diff HEAD --exit-code

      - run:
          name: run tests
          command: npm test

      - store_artifacts:
          path: /home/circleci/.npm/_logs
          destination:  npm-logs

      - store_test_results:
          path: junit
